name: app-frontend
image:
  repository: ghcr.io/ingenieroguardo/app-frontend
  tag: bc130a3
containerPort: 80
env:
  apiUrl: "http://app-api:5000/stats"
ingress:
  enabled: true
  host: frontend.local
