---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-api
  namespace: argocd
spec:
  project: cloud-portfolio
  source:
    repoURL: "https://github.com/ingenieroguardo/cloud-infrastructure-portfolio.git"
    targetRevision: gitops-exercise
    path: gitops-exercise/k8s/helm/base-app
    helm:
      valueFiles:
        - "../../releases/values-api.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-frontend
  namespace: argocd
spec:
  project: cloud-portfolio
  source:
    repoURL: "https://github.com/ingenieroguardo/cloud-infrastructure-portfolio.git"
    targetRevision: gitops-exercise
    path: gitops-exercise/k8s/helm/base-app
    helm:
      valueFiles:
        - "../../releases/values-frontend.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
spec:
  project: cloud-portfolio
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: "https://prometheus-community.github.io/helm-charts"
      targetRevision: 60.0.0
      chart: kube-prometheus-stack
    - repoURL: "https://github.com/ingenieroguardo/cloud-infrastructure-portfolio.git"
      targetRevision: gitops-exercise
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  helm:
    valueFiles:
      - $values/gitops-exercise/k8s/observability/values-prometheus.yaml
