apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: cloud-portfolio
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: "https://github.com/ingenieroguardo/cloud-infrastructure-portfolio.git"
    targetRevision: gitops-exercise
    path: gitops-exercise/k8s/observability
    helm:
      valueFiles:
        - values-prometheus.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
