apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloud-portfolio
  namespace: argocd
spec:
  description: "Proyecto para el ejercicio de GitOps"
  sourceRepos:
    - "*"
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
