apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloud-portfolio
  namespace: argocd
spec:
  sourceRepos:
    - "*"
  destinations:
    - server: "https://kubernetes.default.svc"
      namespace: "default"
    - server: "https://kubernetes.default.svc"
      namespace: "monitoring"
